source 'https://rubygems.org'

gem 'stealth', '~> 2.0'

gem 'railties', '~> 7.0'
gem 'activerecord', '~> 7.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Uncomment to enable the Stealth Facebook Driver
# gem 'stealth-facebook'

# Uncomment to enable the Stealth Twilio SMS Driver
# gem 'stealth-twilio'

group :development do
  gem 'foreman'
  gem 'listen', '~> 3.3'
end
